### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by mdzhangst** [yolandalalala/GNNBoundary#1]
Hello. Thank you very much for the code. However, I found that a gnn_xai_common package was missing during operation, and I did not find the corresponding package on the Internet. Could you please provide me with this package?

**Comment by yolandalalala** [comment]
Hi @mdzhangst, sorry for the confusion. I have updated the dependency specification in `pyproject.toml`. Please try `poetry install` again.

**Comment by mdzhangst** [comment]
Thank you. I have another question. When I ran poetry install, I encountered the following problem. Have you encountered similar problems before? How should I solve it?
![微信图片_20240422153056](https://github.com/yolandalalala/GNNBoundary/assets/55868217/cce52c5e-80b8-4840-be52-a7c9241d0846)
There are solutions to modify the above bugs by providing requirements.txt on the Internet. Can you provide some? Thank you very much.

**Comment by yolandalalala** [comment]
Hi. Can you try to delete the `poetry.lock` file and run `poetry install` again? If it doesn't solve the problem, please try downgrading python to 3.10 and see if it helps.

**Comment by mdzhangst** [comment]
Hello. I have tried. However it fails again.
![微信图片_20240423135016](https://github.com/yolandalalala/GNNBoundary/assets/55868217/f98013f4-b8db-4821-b8aa-9bc374308a28)

**Comment by yolandalalala** [comment]
What is your poetry version?

**Comment by mdzhangst** [comment]
My poetry version is 1.4.

**Comment by yolandalalala** [comment]
Can you try upgrading to 1.8?

**Comment by mdzhangst** [comment]
Yes, I have upgraded to 1.8. There is another bug.
![微信图片_20240423151913](https://github.com/yolandalalala/GNNBoundary/assets/55868217/2779bc20-6876-47c6-b65a-30d615cfddd9)
Maybe it conflicts with my cuda version. I would like to ask, is it convenient for you to provide a requirements.txt? This way I can install the relevant packages directly.

**Comment by yolandalalala** [comment]
I have added a requirements.txt, please give it a try.

**Comment by mdzhangst** [comment]
Thank you very much.
